name: Client
on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/*client*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: cd client && npm ci
      - run: cd client && npm run build
        env:
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_MESSAGE_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_MESSAGE_SENDER_ID }}
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        with:
          args: deploy --only hosting
