name: Client
on:
  push:
    branches:
      - master
    paths:
      - 'client/*'
      - '.github/workflows/*client*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - run: cd client && npm ci
      - run: cd client && npm run build
      # - name: Deploy to Firebase
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy --only hosting:prod
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to firebase
        uses: pizzafox/firebase-action@1.0.7
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: deploy
      # - name: Archive Production Artifact
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: client-dist
      #     path: client/dist
      # - name: Archive Firebase configs
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: .firebaserc
      #     path: .firebaserc
      # - name: Archive Firebase configs
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: firebase.json
      #     path: .firebaserc
