name: Client
on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/*client*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - run: cd client && npm ci
      - run: cd client && npm run build
        env:
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_MESSAGE_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_MESSAGE_SENDER_ID }}
      - name: Deploy to firebase
        uses: pizzafox/firebase-action@1.0.7
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: deploy --only hosting
